UNKNOWN = "unknown"
UNIMPLEMENTED = "unimplemented"
PERMISSION_DENIED_ERROR_CODE = "permission_denied"
NOT_AUTHENTICATED_ERROR_CODE = "not_authenticated"
NOT_FOUND_ERROR_CODE = "not_found"
NOT_CREATED_ERROR_CODE = "not_created"
INVALID_ERROR_CODE = "invalid"
REQUIRED_ERROR_CODE = "required"
