# Generated by Django 3.2 on 2023-03-11 18:50

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.managers
import lava.models.base_models
import lava.utils
import lava.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=lava.utils.get_user_photo_filename, verbose_name='Photo')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='Birth day')),
                ('gender', models.CharField(blank=True, choices=[('', ''), ('F', 'Female'), ('M', 'Male')], default='', max_length=1, verbose_name='Gender')),
                ('country', models.CharField(blank=True, default='', max_length=64, verbose_name='Country')),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='City')),
                ('street_address', models.TextField(blank=True, default='', verbose_name='Street address')),
                ('phone_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Phone number')),
                ('fax', models.CharField(blank=True, default='', max_length=32, verbose_name='Fax')),
                ('job', models.CharField(blank=True, default='', max_length=64, verbose_name='Job title')),
                ('cover_picture', models.ImageField(blank=True, null=True, upload_to=lava.utils.get_user_cover_filename, verbose_name='Cover picture')),
                ('tmp_pwd', models.CharField(blank=True, default='', max_length=64, verbose_name='Temporary password')),
                ('device_id_list', models.JSONField(blank=True, default=list, help_text='A list of devices the the user is connected from.', verbose_name='Device IDs')),
                ('deleted_at', models.DateTimeField(null=True, verbose_name='Deleted at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'ordering': ('-date_joined', 'last_name', 'first_name'),
                'permissions': (('add_user', 'Can add user'), ('change_user', 'Can change user'), ('delete_user', 'Can delete user'), ('soft_delete_user', 'Can soft delete user'), ('view_user', 'Can view user'), ('list_user', 'Can view users list'), ('restore_user', 'Can restore user'), ('change_current_user', 'Can change user profile'), ('delete_current_user', 'Can delete user profile'), ('soft_delete_current_user', 'Can soft delete user profile')),
                'abstract': False,
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
            managers=[
                ('objects', lava.managers.LavaUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_style', models.JSONField(blank=True, default=dict, verbose_name='Font style')),
                ('dark_theme', models.BooleanField(default=False, verbose_name='Dark theme on?')),
                ('list_layout', models.CharField(choices=[('list', 'List'), ('cards', 'Cards')], default='list', max_length=8, verbose_name='List layout')),
                ('menu_layout', models.CharField(choices=[('default', 'Default')], default='default', max_length=16, verbose_name='Menu layout')),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'Français'), ('es', 'Español'), ('ar', 'العربية')], default='en', max_length=2, verbose_name='Language')),
                ('notifications_settings', models.JSONField(blank=True, default=dict, validators=[lava.validators.validate_notifications_settings], verbose_name='Notifications settings')),
            ],
            options={
                'verbose_name': 'Preferences',
                'verbose_name_plural': 'Preferences',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('name',),
                'permissions': (('add_group', 'Can add group'), ('change_group', 'Can update group'), ('delete_group', 'Can delete group'), ('soft_delete_group', 'Can soft delete group'), ('view_group', 'Can view group'), ('list_group', 'Can view group list'), ('view_trash_group', 'Can view deleted groups'), ('restore_group', 'Can restore group')),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=(lava.models.base_models.BaseModelMixin, 'auth.group'),
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
            ],
            options={
                'verbose_name': 'permission',
                'verbose_name_plural': 'permissions',
                'ordering': ['content_type__app_label', 'content_type__model', 'codename'],
                'permissions': (('add_permission', 'Can add permissions'), ('view_permission', 'Can view permission details'), ('change_permission', 'Can update permissions'), ('delete_permission', 'Can delete permissions'), ('list_permission', 'Can view permissions list'), ('set_permission', 'Can set permissions'), ('export_permissions', 'Can export permissions')),
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=(lava.models.base_models.BaseModelMixin, 'auth.permission'),
            managers=[
                ('objects', django.contrib.auth.models.PermissionManager()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date sent')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('content', models.TextField(blank=True, default='', verbose_name='Content')),
                ('category', models.CharField(choices=[('alert', 'Alert')], default='alert', max_length=32, verbose_name='Category')),
                ('url', models.CharField(blank=True, default='', help_text='Action URL', max_length=200, validators=[lava.validators.SchemelessURLValidator()], verbose_name='URL')),
                ('seen_by', models.JSONField(blank=True, default=list, verbose_name='Seen by')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('target_groups', models.ManyToManyField(blank=True, related_name='notifications', to='lava.Group')),
                ('target_users', models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(blank=True, max_length=256, verbose_name='Backup name')),
                ('type', models.CharField(choices=[('full_backup', 'Full backup'), ('db_backup', 'Database backup')], default='full_backup', max_length=16, verbose_name='Backup type')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Status')),
                ('backup_file', models.FileField(blank=True, null=True, upload_to=lava.utils.get_backup_file_filename, verbose_name='Backup file')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ('-created_at',),
                'permissions': (('add_backup', 'Can add backup'), ('delete_backup', 'Can delete backup'), ('soft_delete_backup', 'Can soft delete backup'), ('list_backup', 'Can view backup')),
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', related_query_name='user', to='lava.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='lava.preferences'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='users', related_query_name='user', to='lava.Permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lava.group',),
        ),
    ]
