# Generated by Django 3.2 on 2022-07-30 19:36

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lava.utils.get_user_photo_filename,
                        verbose_name="Photo",
                    ),
                ),
                (
                    "birth_day",
                    models.DateField(blank=True, null=True, verbose_name="Birth day"),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("", ""), ("F", "Female"), ("M", "Male")],
                        default="",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Country"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="City"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, default="", verbose_name="Address"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=32,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "fax",
                    models.CharField(
                        blank=True, default="", max_length=32, verbose_name="Fax"
                    ),
                ),
                (
                    "job",
                    models.CharField(
                        blank=True, default="", max_length=64, verbose_name="Job title"
                    ),
                ),
                (
                    "cover_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=lava.utils.get_user_cover_filename,
                        verbose_name="Cover picture",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="users",
                        related_query_name="user",
                        to="auth.Group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "ordering": ("-date_joined", "last_name", "first_name"),
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Preferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "font_style",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Font style"
                    ),
                ),
                (
                    "dark_theme",
                    models.BooleanField(default=False, verbose_name="Dark theme on?"),
                ),
                (
                    "list_layout",
                    models.CharField(
                        choices=[("list", "List"), ("cards", "Cards")],
                        default="list",
                        max_length=8,
                        verbose_name="List layout",
                    ),
                ),
                (
                    "menu_layout",
                    models.CharField(
                        choices=[("default", "Default")],
                        default="default",
                        max_length=16,
                        verbose_name="Menu layout",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("es", "Español"),
                            ("ar", "العربية"),
                        ],
                        default="en",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Preferences",
                "verbose_name_plural": "Preferences",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Date sent"),
                ),
                ("title", models.CharField(max_length=128, verbose_name="Title")),
                (
                    "content",
                    models.TextField(blank=True, default="", verbose_name="Content"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("alert", "Alert")],
                        default="alert",
                        max_length=32,
                        verbose_name="Category",
                    ),
                ),
                (
                    "target_groups",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Target groups"
                    ),
                ),
                (
                    "target_users",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Target users"
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.OneToOneField(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="lava.preferences",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="users",
                related_query_name="user",
                to="auth.Permission",
                verbose_name="user permissions",
            ),
        ),
    ]
