# Generated by Django 3.2 on 2022-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='Street address'),
        ),
    ]
