# Generated by Django 3.2 on 2022-08-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tmp_pwd',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Temporary password'),
        ),
    ]
