# Generated by Django 3.2 on 2023-03-14 17:00

from django.db import migrations
import easy_thumbnails.fields
import lava.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0002_logentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_picture',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, help_text='Preferred image dimentions: (1200 x 250)', null=True, upload_to=lava.utils.get_user_cover_filename, verbose_name='Cover picture'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=lava.utils.get_user_photo_filename, verbose_name='Photo'),
        ),
    ]
