# Generated by Django 3.2 on 2022-08-29 12:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lava', '0003_user_tmp_pwd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-date',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_groups',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='auth.Group'),
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_users',
        ),
        migrations.AddField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
