# Generated by Django 3.2 on 2023-03-17 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.models.base_models
import lava.validators


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0004_auto_20230316_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('street_address', models.CharField(blank=True, max_length=256, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=256, verbose_name='Code postal')),
                ('city', models.CharField(max_length=256, validators=[lava.validators.validate_empty_field], verbose_name='Ville')),
                ('country', models.CharField(max_length=256, validators=[lava.validators.validate_empty_field], verbose_name='Pays')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ('city', 'country', 'street_address'),
                'abstract': False,
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
    ]
