# Generated by Django 3.2 on 2023-10-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0004_auto_20231004_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='iban',
            field=models.CharField(blank=True, max_length=34, verbose_name='IBAN'),
        ),
    ]
