# Generated by Django 3.2 on 2022-09-11 18:16

from django.db import migrations, models
import lava.validators


class Migration(migrations.Migration):

    dependencies = [
        ("lava", "0004_auto_20220829_1236"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Action URL",
                validators=[lava.validators.SchemelessURLValidator()],
                verbose_name="URL",
            ),
        ),
    ]
