# Generated by Django 3.2 on 2022-09-15 09:12

from django.db import migrations, models
import lava.validators


class Migration(migrations.Migration):

    dependencies = [
        ("lava", "0005_notification_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="preferences",
            name="notifications_settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                validators=[lava.validators.validate_notifications_settings],
                verbose_name="Notifications settings",
            ),
        ),
    ]
