# Generated by Django 3.2 on 2023-03-19 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import lava.models.base_models
import lava.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lava', '0005_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AlterModelOptions(
            name='logentry',
            options={'default_permissions': (), 'ordering': ['-action_time'], 'permissions': (('list_log_entry', 'Can view activity journal'), ('export_log_entry', 'Can export activity journal')), 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'default_permissions': (), 'ordering': ('-date',), 'permissions': (('list_notification', 'Can list notifications'), ('add_notification', 'Can add notification'), ('view_notification', 'Can view notification'), ('delete_notification', 'Can delete notification')), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to=lava.utils.get_group_photo_filename, verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_groups', to='lava.group', verbose_name='Parent')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('-created_at',),
                'abstract': False,
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, 'auth.group', models.Model),
        ),
        migrations.AlterField(
            model_name='User',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', related_query_name='user', to='lava.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='Notification',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lava.Group'),
        ),
    ]
