# Generated by Django 3.2 on 2023-03-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0006_auto_20230319_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='notification_id',
            field=models.CharField(blank=True, max_length=256, verbose_name='Notification group id'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='Full name'),
        ),
    ]
