# Generated by Django 3.2 on 2022-09-15 09:25

from django.db import migrations, models
import lava.validators


class Migration(migrations.Migration):

    dependencies = [
        ("lava", "0006_preferences_notifications_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Action URL",
                max_length=200,
                validators=[lava.validators.SchemelessURLValidator()],
                verbose_name="URL",
            ),
        ),
    ]
