# Generated by Django 3.2 on 2022-09-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lava", "0007_alter_notification_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="seen_by",
            field=models.JSONField(blank=True, default=list, verbose_name="Seen by"),
        ),
    ]
