# Generated by Django 3.2 on 2023-03-23 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0008_bank_bankaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='account_holder',
            field=models.CharField(blank=True, max_length=256, verbose_name='Account holder'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lava.bank', verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Name'),
        ),
    ]
