# Generated by Django 3.2 on 2023-04-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.models.base_models
import lava.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0009_auto_20230323_1657'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('is_group_conversation', models.BooleanField(default=False, verbose_name='Group conversation')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=lava.utils.get_conversation_logo_filename, verbose_name='Logo')),
                ('members', models.JSONField(default=dict, verbose_name='Members')),
                ('pinned_at', models.DateTimeField(blank=True, null=True, verbose_name='Pinned at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ('-pinned_at', '-messages__created_at'),
                'abstract': False,
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lava.utils.get_chat_message_image_filename, verbose_name='Image')),
                ('type', models.CharField(choices=[('text', 'Text'), ('image', 'Image')], default='email', max_length=32, verbose_name='Message type')),
                ('read_by', models.JSONField(default=dict, verbose_name='Read by')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='lava.conversation', verbose_name='Conversation')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ('created_at',),
                'abstract': False,
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
    ]
