# Generated by Django 3.2 on 2022-12-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0009_user_device_id_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deleted_at',
            field=models.DateTimeField(null=True, verbose_name='Deleted at'),
        ),
    ]
