# Generated by Django 3.2 on 2023-04-07 11:08

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):
    dependencies = [
        ("lava", "0010_chatmessage_conversation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conversation",
            options={
                "default_permissions": (),
                "ordering": (
                    "-pinned_at",
                    django.db.models.expressions.OrderBy(
                        django.db.models.expressions.F("last_updated_at"),
                        descending=True,
                        nulls_last=True,
                    ),
                ),
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
            },
        ),
    ]
