# Generated by Django 3.2 on 2023-01-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0010_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_users',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lava.User'),
        ),
    ]
