# Generated by Django 3.2 on 2023-04-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0011_alter_conversation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='routing_number',
            field=models.CharField(blank=True, max_length=9, verbose_name='Routing number'),
        ),
    ]
