# Generated by Django 3.2 on 2023-01-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0011_alter_notification_target_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='address',
            new_name='street_address',
        ),
    ]
