# Generated by Django 3.2 on 2023-01-09 15:50

from django.db import migrations
import lava.managers


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0012_rename_address_user_street_address'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', lava.managers.LavaUserManager()),
            ],
        ),
    ]
