# Generated by Django 3.2 on 2023-01-17 17:05

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import lava.utils


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lava', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to=lava.utils.get_group_photo_filename, verbose_name='Image')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_groups', to='lava.group', verbose_name='Parent')),
                ('permissions', models.ManyToManyField(blank=True, related_name='lava_groups', to='auth.Permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('-created_at',),
                'permissions': (('add_group', 'Can add group'), ('change_group', 'Can update group'), ('delete_group', 'Can delete group'), ('soft_delete_group', 'Can soft delete group'), ('view_group', 'Can view group'), ('list_group', 'Can view group list'), ('view_trash_group', 'Can view deleted groups'), ('restore_group', 'Can restore group')),
                'abstract': False,
                'default_permissions': (),
            },
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lava.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', related_query_name='user', to='lava.Group', verbose_name='groups'),
        ),
    ]
