# Generated by Django 3.2 on 2023-01-18 13:41

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('lava', '0013_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ('name',),
                'permissions': (('add_group', 'Can add group'), ('change_group', 'Can update group'), ('delete_group', 'Can delete group'), ('soft_delete_group', 'Can soft delete group'), ('view_group', 'Can view group'), ('list_group', 'Can view group list'), ('view_trash_group', 'Can view deleted groups'), ('restore_group', 'Can restore group')),
                'abstract': False,
                'proxy': True,
                'default_permissions': (),
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_groups',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='lava.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='users', related_query_name='user', to='lava.Group', verbose_name='groups'),
        ),
    ]
