# Generated by Django 3.2 on 2023-06-06 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0013_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'default_permissions': (), 'ordering': ['-action_time'], 'permissions': (('list_logentry', 'Can view activity journal'), ('export_logentry', 'Can export activity journal')), 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
    ]
