# Generated by Django 3.2 on 2023-06-20 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0014_alter_logentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('name', models.CharField(blank=True, default='', max_length=256, verbose_name='Name')),
                ('document_file', models.FileField(upload_to='documents', verbose_name='File')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
    ]
