# Generated by Django 3.2 on 2023-06-23 22:00

from django.db import migrations, models
import lava.utils.handle_upload_filenames


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0015_filedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='agency',
            field=models.CharField(blank=True, max_length=256, verbose_name='Agency'),
        ),
        migrations.AddField(
            model_name='bank',
            name='city',
            field=models.CharField(blank=True, max_length=256, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='filedocument',
            name='document_file',
            field=models.FileField(upload_to=lava.utils.handle_upload_filenames.get_document_filename, verbose_name='File'),
        ),
    ]
