# Generated by Django 3.2 on 2023-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0016_auto_20230623_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='user',
            name='extra_fields',
            field=models.JSONField(default=dict, verbose_name='Extra fields'),
        ),
    ]
