# Generated by Django 3.2 on 2023-01-24 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0018_auto_20230123_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'default_permissions': (), 'ordering': ['-action_time'], 'permissions': (('list_logentry', 'Can view activity journal'), ('export_logentry', 'Can export activity journal')), 'verbose_name': 'Log entry', 'verbose_name_plural': 'Log entries'},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'default_permissions': (), 'ordering': ['content_type__app_label', 'content_type__model', 'codename'], 'permissions': (('add_permission', 'Can add permissions'), ('view_permission', 'Can view permission details'), ('change_permission', 'Can update permissions'), ('delete_permission', 'Can delete permissions'), ('list_permission', 'Can view permissions list'), ('set_permission', 'Can set permissions'), ('export_permissions', 'Can export permissions')), 'verbose_name': 'permission', 'verbose_name_plural': 'permissions'},
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Last update'),
        ),
    ]
