# Generated by Django 3.2 on 2023-02-10 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import lava.models.base_models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0020_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Created at')),
                ('last_updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Last update')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('type', models.CharField(choices=[('full_backup', 'Full backup'), ('db_backup', 'Database backup')], default='full_backup', max_length=16, verbose_name='Backup type')),
                ('status', models.CharField(choices=[('created', 'Created'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='created', max_length=16, verbose_name='Status')),
                ('path', models.CharField(blank=True, max_length=256, null=True, verbose_name='Backup Path')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'permissions': (('add_backup', 'Can add backup'), ('change_backup', 'Can update backup'), ('delete_backup', 'Can delete backup'), ('soft_delete_backup', 'Can soft backup'), ('view_backup', 'Can view backup'), ('list_backup', 'Can view backup'), ('restore_backup', 'Can restore backup')),
                'default_permissions': (),
            },
            bases=(lava.models.base_models.BaseModelMixin, models.Model),
        ),
    ]
