# Generated by Django 3.2 on 2023-02-10 14:15

from django.db import migrations, models
import lava.utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0021_backup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backup',
            options={'default_permissions': (), 'ordering': ('-created_at',), 'permissions': (('add_backup', 'Can add backup'), ('change_backup', 'Can update backup'), ('delete_backup', 'Can delete backup'), ('soft_delete_backup', 'Can soft backup'), ('view_backup', 'Can view backup'), ('list_backup', 'Can view backup'), ('restore_backup', 'Can restore backup')), 'verbose_name': 'Backup', 'verbose_name_plural': 'Backups'},
        ),
        migrations.RemoveField(
            model_name='backup',
            name='path',
        ),
        migrations.AddField(
            model_name='backup',
            name='backup_file',
            field=models.FileField(blank=True, null=True, upload_to=lava.utils.utils.get_backup_file_filename, verbose_name='Backup file'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=16, verbose_name='Status'),
        ),
    ]
