# Generated by Django 3.2 on 2023-02-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0023_alter_backup_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='name',
            field=models.CharField(blank=True, max_length=256, verbose_name='Backup name'),
        ),
    ]
