# Generated by Django 3.2 on 2023-02-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lava', '0024_backup_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lava.group',),
        ),
    ]
